name: Use Basis main Stufe 4 main.yml

# Controls when the action will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    paths:
    - 'Resources/**'
    branches-ignore:
    - 'main**'
  pull_request:
    branches:
    - 'main**'

  # Allows you to run this workflow manually from the Actions tab      
  workflow_dispatch: 

    
jobs:
  call-tool-update:
    uses: gematik/spec-isik-basismodul/.github/workflows/main.yml@main-stufe-4
    secrets:
      SIMPLIFIER_USERNAME: ${{ secrets.SIMPLIFIER_USERNAME }}
      SIMPLIFIER_PASSWORD: ${{ secrets.SIMPLIFIER_PASSWORD }}
      WORKFLOW_PERMISSION_GITHUB: ${{ secrets.WORKFLOW_PERMISSION_GITHUB }}      